blog/urls.py
from django.urls import path, include
from .feeds import LatestPostFeed
from .import views
app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post-list'),
    path('post-details/<slug:slug>/', views.post_details, name='post-details'),
    path('share-post/<str:pk>', views.share_post, name='share-post'),
    path('create-comment/<str:pk>/', views.create_comment, name='create-comment'),
    path('user-login/', views.user_login, name='user-login'),
    path('user-logout/',  views.user_logout, name='user-logout'),
    path('create-user/', views.create_user, name='create-user'),
    path('view-myblog/', views.view_myblog, name='view-myblog'),
    path('create-post/', views.create_post, name='create-post'),
    path('feed/', LatestPostFeed(), name='post-feed'),
    path('search/', views.do_search, name='do-search'),
]

blogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.db.models import UniqueConstraint
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import User
import uuid

# Create your models here.

class Post(models.Model):
    STATUS_OF_POST = [
        ('DF','DRAFT'),('PB','PUBLISHED'),
    ]
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True, blank=True)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=STATUS_OF_POST, default='DF')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False, null=False)

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish']),]
    

    def save(self, *args, **kwargs):
        
        self.slug = slugify(self.title)
        
        super(Post, self).save(*args, **kwargs)
    
    
    def __str__(self):
        return self.title

    
    def get_absolute_url(self):
        return reverse('blog:post-details', args=[self.slug])



class Comment(models.Model):

    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    name = models.CharField(max_length=80)
    email = models.EmailField(max_length=254)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')

    class Meta:
        constraints =[UniqueConstraint(fields=['email','post'], name='unique_email_post')

        ]
        ordering =['created_on']
    

    
    def __str__(self):
        return f"Comment by {self.name} on {self.post}"
    

blog/forms.py
from django import forms
from .models import Comment
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import Post

class SharePostForm(forms.Form):
    Name = forms.CharField(max_length=25, required=True)
    Email = forms.EmailField(required=True)
    to = forms.EmailField(required=True)
    comment = forms.CharField(required=False, widget=forms.Textarea)


    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, obj in self.fields.items():
            obj.widget.attrs['class'] = 'form-control'



class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for key, obj in self.fields.items():
            obj.widget.attrs['class'] = 'form-control'
        
    

class CustomAuthenticationForm(AuthenticationForm):

    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for key, obj in self.fields.items():
            obj.widget.attrs['class'] = 'form-control'
        

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
    
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for key, obj in self.fields.items():
            obj.widget.attrs['class'] = 'form-control'
        
    

class AddPost(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'body']

    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for key, obj in self.fields.items():
            obj.widget.attrs['class'] = 'form-control'
        
    

       
          

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from .models import Post
from .forms import SharePostForm, CommentForm, CustomAuthenticationForm, CustomUserCreationForm
from django.core.mail import send_mail
from django.conf import settings
from django.db import IntegrityError
from django.contrib.auth import authenticate, login, logout
from .forms import AddPost
from django.contrib.postgres.search import SearchVector, SearchQuery
from django.contrib.auth.decorators import login_required

from django.contrib import messages


# Create your views here.

def post_list(request):
    posts = Post.objects.filter(status='PB')
    upcoming = Post.objects.filter(status='DF')[:3]
    pages = Paginator(posts, 2)
    page_number = request.GET.get('page', 1)
    page = pages.get_page(page_number)
    posts = page.object_list

    start_index = page.number - 1
    if start_index < 1:
        start_index = 1
    
    end_index = page.number + 3
    if end_index > pages.num_pages:
        end_index = (pages.num_pages) + 1
    
    custom_range = range(start_index,end_index)    
    
    context = {'posts': posts, 'upcoming': upcoming, 'pages': pages, 'page': page, 'custom_range': custom_range}
    return render(request, 'blog/post-list.html', context)

def post_details(request, slug):
    # post = Post.objects.get(slug=slug)
    post = get_object_or_404(Post, slug=slug)
    form =  CommentForm()
    comments = post.comments.filter(active=True)
    context = {'post': post, 'form': form, 'comments': comments}
    return render(request, 'blog/post-details.html', context)


@login_required(login_url='blog:user-login')
def view_myblog(request):
    owner = request.user
    posts = Post.objects.filter(owner=owner)
    context = {'posts': posts}
    return render(request, 'blog/view-myblog.html', context)


def share_post(request, pk):
    form = SharePostForm()
    post = get_object_or_404(Post, id=pk, status='PB')
    if request.method == 'POST':
        form = SharePostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['Name']} recommends you to read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                    f"{cd['Name']}\'s comments: {cd['comment']}"
            

            send_mail(
            subject,
            message,
            settings.EMAIL_HOST_USER,
            [cd['to']],
            fail_silently=False,
        )
        return redirect('blog:post-list')

    context = {'form': form}
    return render(request, 'blog/share-post.html', context)

def create_post(request):
    owner = request.user
    if request.method == 'POST':
        form = AddPost(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = owner
            new_post.save()
            return redirect('blog:view-myblog')
    else:

        form = AddPost()
    context = {'form': form}
    return render(request, 'blog/create-post.html', context)



def create_comment(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            try:
                new_comment.post = post
                new_comment.save()
            except IntegrityError:
                print(' You have already given the comment.')

            return redirect('blog:post-details', slug=post.slug)
        else:
            print('Error in saving comment.')
        
    
def user_login(request):
    
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request,user)
                return redirect('blog:post-list')
            
    else:
        form = CustomAuthenticationForm()
            
    context = {'form': form}
    return render(request, 'blog/user_login.html', context)


def user_logout(request):

    logout(request)
    return redirect('blog:post-list')


def create_user(request):
    
    if request.method == 'POST':
        print('enter in post')
        form = CustomUserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            print('save data')
            return redirect('blog:user-login')
    else:
        form = CustomUserCreationForm()

    context = {'form': form}
    return render(request, 'blog/create_user.html', context)


def do_search(request):
    query = request.GET.get('query', '')
    search_vector = SearchVector('title', 'body')
    search_query = SearchQuery(query)
    results = Post.objects.annotate(search=search_vector).filter(search=search_query)
    print(results)
    if not results:
        messages.error(request, 'There is no data in the database. Please Try again...')
    
    context = {'results': results}
    
    return render(request, 'blog/post-list.html', context)

blog/templates/blog/comment_form.html
{% block content %}
<h4>Add New Comment</h4>
    <form action="{% url 'blog:create-comment' post.id %}" method="post">
        <div class="mb-3">
            
            {% csrf_token %}
            {% for field in form %}
            <label class="form-label">{{ field.label }}</label>
            {{ field }}
            {% endfor %}
        </div>

        <input type="submit" class="btn btn-primary" value="Add Comment">
    </form>
{% endblock content %}
    

blog/templates/blog/create-post.html
{% extends 'base.html' %}

{% block content %}
<h4>Add New Post</h4>
    <form action="" method="post">
        <div class="mb-3">
            
            {% csrf_token %}
            {% for field in form %}
            <label class="form-label">{{ field.label }}</label>
            {{ field }}
            {% endfor %}
        </div>

        <input type="submit" class="btn btn-primary" value="Add Post">
    </form>
{% endblock content %}

blog/templates/blog/create_user.html
{% extends 'base.html' %}


{% block content %}

<h3>Create Account</h3>
 
<form action="{% url 'blog:create-user' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="mb-3">
        <label class="form-label">{{ field.label }}</label>
        <div class="col-sm-4">
            {{ field }}

        </div>

    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}
    

blog/templates/blog/post-details.html
{% extends 'base.html' %}


{% block content %}
    
<h1 class="display-6">{{ post.title }}</h1>
<p class="text-body-secondary"><em>{{ post.publish }}</em></p>
<p class="lead">{{ post.body | linebreaks }}</p>
<a class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" href="{% url 'blog:share-post' post.id %}">
    <strong>Share the Post</strong>
</a>

{% with comments.count as total_comments %}
  <h5>Total Comments({{ total_comments }})</h5>
{% endwith %}


{% for comment in comments %}

  <p class="text-muted fw-bold small"><em>Comment by {{ comment.name }} at {{ comment.created_on }}</em></p>
  <p class="lead">{{ comment.body | linebreaks }}</p>
{% empty %}
  <p>There are no comments yet.</p>
{% endfor %}
  

{% include 'blog/comment_form.html' %}
{% endblock content %}
    

blog/templates/blog/post-list.html
{% extends 'base.html' %}

{% block content %}
    <!-- Blog Posts -->
    
    <div class="row">
        <div class="col-md-8">
            <h2 class="pb-4">Featured Blog Posts</h2>
            <!-- {% if messages %}
                
                    {% for message in messages %}

                    <div class="alert alert-danger">
                        {{ message }}
                    </div>
                    
                    {% endfor %}
                
            {% endif %} -->
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-dismissible fade show alert-danger text-danger fw-bold" role="alert">
                        {{ message }}
                        <form action="{% url 'blog:post-list' %}">
                            <button type="submit" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </form>
                        
                    </div>
                {% endfor %}
            {% endif %}

            
            <!-- Blog Post 1 -->
            {% if results %}
                {% for post in results %}
                    <div class="card mb-4">
                        <!-- <img src="blog-post-1.jpg" class="card-img-top" alt="Blog Post 1"> -->
                        <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p class="text-muted small"><em>{{ post.publish }}</em> by {{ post.owner.username }}</p>
                            <p class="card-text">{{ post.body |truncatewords:30|linebreaks }}</p>
                            <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More</a>
                        </div>
                    </div>
                {% endfor %}    
            {% else %}
                
                {% for post in posts %}
            
                    <div class="card mb-4">
                        <!-- <img src="blog-post-1.jpg" class="card-img-top" alt="Blog Post 1"> -->
                        <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p class="text-muted small"><em>{{ post.publish }}</em> by {{ post.owner.username }}</p>
                            <p class="card-text">{{ post.body |truncatewords:30|linebreaks }}</p>
                            <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More</a>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
            
        </div>
        {% if results == null %}
            <div class="col-md-4">
                <!-- Sidebar -->
                <h2 class="pb-4">Upcoming Posts</h2>
                <!-- Upcoming Post 1 -->
                {% for post in upcoming %}
                <div class="card mb-4">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">{{ post.created_on }}</p>
                    </div>
                </div>
                {% endfor %}
                <p><a href="{% url 'blog:post-feed' %}">Subscribe to my RSS Feed</a></p>
                
            </div>
        {% endif %}
    </div>
    <!-- {% for post in posts %}

        <a class=" link-underline link-underline-opacity-0" href="{% url 'blog:post-details' post.slug %}"><h3 class="display-6">{{ post.title }}</h3></a>
        <p class="text-body-secondary"><em>{{ post.publish }}</em></p>
        <p class="lead">{{ post.body | truncatewords:60 | linebreaks }}</p>
        

    {% endfor %} -->
    {% include 'pagination.html' %}
{% endblock content %}
    

blog/templates/blog/share-post.html
{% extends 'base.html' %}


{% block content %}

    <form action="" method="post">
        <div class="mb-3">
            {% csrf_token %}
            {% for field in form %}
            <label class="form-label">{{ field.label }}</label>
            {{ field }}
            {% endfor %}
        </div>

        <input type="submit" class="btn btn-primary" value="Send Email">
    </form>

{% endblock content %}
    

blog/templates/blog/user_login.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'blog:user-login' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="mb-3">
        <label class="form-label">{{ field.label }}</label>
        <div class="col-sm-4">
            {{ field }}

        </div>

    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
    
        

   
{% endblock content %}
    

blog/templates/blog/view-myblog.html
{% extends 'base.html' %}


{% block content %}
    
<div class="row">
    <div class="col-md-8">
        <h2 class="pb-4">All Blog Posts</h2>
        <a href="{% url 'blog:create-post' %}">Add Post</a>
        <!-- Blog Post 1 -->
        {% for post in posts %}
        <div class="card mb-4">
            <!-- <img src="blog-post-1.jpg" class="card-img-top" alt="Blog Post 1"> -->
            <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="text-muted small"><em>{{ post.publish }}</em> by {{ post.owner.username }} Current status: {{ post.status }}</p>
                <p class="card-text">{{ post.body |truncatewords:30|linebreaks }}</p>
                
            </div>
        </div>
        {% empty %}
        <p class="lead">There are no post yet.</p>

        {% endfor %}
        
    </div>
    
</div>
{% endblock content %}


    