blog/urls.py
from django.urls import path, include
from .feeds import LatestPostFeed
from .import views
app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post-list'),
    path('post-details/<slug:slug>/', views.post_details, name='post-details'),
    path('share-post/<str:pk>', views.share_post, name='share-post'),
    path('create-comment/<str:pk>/', views.create_comment, name='create-comment'),
    path('user-login/', views.user_login, name='user-login'),
    path('user-logout/',  views.user_logout, name='user-logout'),
    path('create-user/', views.create_user, name='create-user'),
    path('view-myblog/', views.view_myblog, name='view-myblog'),
    path('create-post/', views.create_post, name='create-post'),
    path('feed/', LatestPostFeed(), name='post-feed'),
    path('search/', views.do_search, name='do-search'),
]

blogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog Application</title>
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body class="d-flex flex-column min-vh-100">
    {% include 'header.html' %}
    <div class="container mt-5 flex-fill">
        <!-- Content here -->
        
    
        {% block content %}
            
        {% endblock content %}

        
    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </div>
    {% include 'footer.html' %}
  </body>
</html>

templates/footer.html
<!-- Footer -->
<footer class="bg-light text-dark text-center py-3 footer">
  <div class="container">
      &copy; 2023 Sadique Naikwadi
  </div>
</footer>

templates/header.html
  <!-- Navbar -->
  <nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:post-list' %}">My Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:post-list' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:view-myblog' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
            <div class="d-flex align-items-center">
            <form action="{% url 'blog:do-search' %}">   
                <input class="form-control search-box me-2" type="search" name="query" placeholder="Search">
            </form>
            {% if request.user.is_authenticated %}
            <a href="{% url 'blog:user-logout' %}"><button class="btn btn-primary login-btn me-2">Logout</button></a>
            {% else %}
                <a href="{% url 'blog:user-login' %}"><button class="btn btn-primary login-btn me-2">Login</button></a>
                <a href="{% url 'blog:create-user' %}"><button class="btn btn-success  signup-btn me-2 text-nowrap">Sign Up</button></a>
            {% endif %}
            </div>
            
        </div>
        </div>
    </div>
</nav>

templates/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item">
        {% if page.has_previous %}
        <a class="page-link" href="?page={{ page.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
        {% endif %}
      </li>
      
      {% for page_number in custom_range %}

        {% if page_number == page.number %}
      
            <li class="page-item active"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
        {% endif %}
      {% endfor %}
      <li class="page-item">
        {% if page.has_next %}
        <a class="page-link" href="?page={{ page.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
        {% endif %}
      </li>
    </ul>
</nav>